import json
import os
import re
import sys
from copy import deepcopy
from pathlib import Path
from typing import Any

import requests

CHAT_COMPLETIONS_URL = "https://api.openai.com/v1/chat/completions"

SPEC_CANDIDATES = [
    Path("specs/app.json"),
    Path("specs/init.json"),
]

GOAL_PATH = Path("goal.json")
QUEUE_PATH = Path("tasks/queue.json")
STATE_PATH = Path("tasks/state.json")

FORBIDDEN_PREFIXES = (
    ".git/",
    ".github/workflows/",
)

SUPPORTED_TASKS = {
    "strengthen_contract": "Convert legacy API spec into typed contract form with system/api/response schema structure.",
    "add_post_echo": "Ensure a typed POST /echo endpoint exists with request.text -> response.echo mapping.",
}

PLANNER_SCHEMA = {
    "name": "task_plan",
    "strict": True,
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "tasks": {
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": list(SUPPORTED_TASKS.keys()),
                }
            }
        },
        "required": ["tasks"],
    },
}

OUTPUT_SCHEMA = {
    "name": "generated_files",
    "strict": True,
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "files": {
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "path": {"type": "string"},
                        "content": {"type": "string"},
                    },
                    "required": ["path", "content"],
                },
            }
        },
        "required": ["files"],
    },
}


def fail(message: str) -> None:
    print(f"ERROR: {message}")
    sys.exit(1)


def read_json(path: Path, default: Any | None = None) -> Any:
    if not path.exists():
        if default is not None:
            return default
        fail(f"Missing required file: {path.as_posix()}")
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def read_spec() -> tuple[Path, dict]:
    for path in SPEC_CANDIDATES:
        if path.exists():
            with path.open("r", encoding="utf-8") as f:
                return path, json.load(f)
    fail("No spec found. Expected specs/app.json or specs/init.json.")


def save_spec(spec_path: Path, spec: dict) -> None:
    spec_path.parent.mkdir(parents=True, exist_ok=True)
    spec_path.write_text(json.dumps(spec, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def call_openai_json(messages: list[dict], schema: dict) -> dict:
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        fail("OPENAI_API_KEY not set.")

    response = requests.post(
        CHAT_COMPLETIONS_URL,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": os.getenv("OPENAI_MODEL", "gpt-4o-mini"),
            "messages": messages,
            "response_format": {
                "type": "json_schema",
                "json_schema": schema,
            },
            "temperature": 0,
        },
        timeout=180,
    )

    if response.status_code != 200:
        fail(f"OpenAI error: {response.status_code} {response.text}")

    data = response.json()

    try:
        content = data["choices"][0]["message"]["content"]
        return json.loads(content)
    except Exception as e:
        fail(f"Invalid JSON from model: {e}")


def is_contract_spec(spec: dict) -> bool:
    return isinstance(spec, dict) and "system" in spec and "api" in spec and isinstance(spec["api"], dict)


def to_contract_spec(spec: dict) -> dict:
    if is_contract_spec(spec):
        return spec

    name = spec.get("name", "meta-dev-api")
    system_type = spec.get("type", "fastapi")
    description = spec.get("description", "Typed API generated by meta software factory")

    legacy_endpoints = spec.get("endpoints", [])
    new_endpoints = []

    for ep in legacy_endpoints:
        method = ep.get("method", "GET").upper()
        path = ep.get("path", "/")
        response_obj = ep.get("response", {})

        schema = {}
        if isinstance(response_obj, dict):
            for key, value in response_obj.items():
                inferred_type = "string"
                if isinstance(value, bool):
                    inferred_type = "boolean"
                elif isinstance(value, int):
                    inferred_type = "integer"
                elif isinstance(value, float):
                    inferred_type = "number"
                elif isinstance(value, list):
                    inferred_type = "array"
                elif isinstance(value, dict):
                    inferred_type = "object"

                schema[key] = {
                    "type": inferred_type,
                    "example": value,
                }

        new_endpoints.append(
            {
                "name": ep.get("name", path.strip("/").replace("/", "_") or "root"),
                "method": method,
                "path": path,
                "description": ep.get("description", f"{method} {path} endpoint"),
                "response": {
                    "type": "object",
                    "schema": schema,
                },
            }
        )

    return {
        "system": {
            "name": name,
            "type": system_type,
            "description": description,
        },
        "api": {
            "basePath": "/",
            "endpoints": new_endpoints,
        },
    }


def ensure_post_echo(spec: dict) -> dict:
    spec = to_contract_spec(spec)
    endpoints = spec.setdefault("api", {}).setdefault("endpoints", [])

    for ep in endpoints:
        if ep.get("method", "").upper() == "POST" and ep.get("path") == "/echo":
            return spec

    endpoints.append(
        {
            "name": "echo",
            "method": "POST",
            "path": "/echo",
            "description": "Echo input data",
            "request": {
                "type": "object",
                "schema": {
                    "text": {
                        "type": "string",
                        "example": "hello"
                    }
                }
            },
            "response": {
                "type": "object",
                "schema": {
                    "echo": {
                        "type": "string",
                        "example": "hello"
                    }
                }
            }
        }
    )
    return spec


def heuristic_plan(goal: str, spec: dict) -> list[str]:
    goal_l = goal.lower()
    tasks: list[str] = []

    if not is_contract_spec(spec):
        tasks.append("strengthen_contract")

    if any(token in goal_l for token in ["post", "echo", "typed", "input"]):
        tasks.append("add_post_echo")

    return dedupe(tasks)


def dedupe(items: list[str]) -> list[str]:
    seen = set()
    result = []
    for item in items:
        if item not in seen:
            result.append(item)
            seen.add(item)
    return result


def plan_tasks(goal: str, spec: dict) -> list[str]:
    heuristic = heuristic_plan(goal, spec)

    messages = [
        {
            "role": "developer",
            "content": (
                "You are a deterministic task planner for a software factory. "
                "Choose only from the supported task IDs. "
                "Return the minimum ordered task list needed to satisfy the goal. "
                "Do not invent task IDs."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Goal: {goal}\n\n"
                f"Current spec:\n{json.dumps(spec, indent=2, ensure_ascii=False)}\n\n"
                "Supported tasks:\n"
                + "\n".join(f"- {k}: {v}" for k, v in SUPPORTED_TASKS.items())
            ),
        },
    ]

    try:
        planned = call_openai_json(messages, PLANNER_SCHEMA).get("tasks", [])
        planned = [task for task in planned if task in SUPPORTED_TASKS]
        combined = dedupe(heuristic + planned)
        return combined
    except Exception:
        return heuristic


def apply_task(spec: dict, task_id: str) -> dict:
    updated = deepcopy(spec)

    if task_id == "strengthen_contract":
        return to_contract_spec(updated)

    if task_id == "add_post_echo":
        updated = to_contract_spec(updated)
        return ensure_post_echo(updated)

    fail(f"Unsupported task: {task_id}")
    return updated


def build_generation_messages(spec_path: Path, spec: dict) -> list[dict]:
    return [
        {
            "role": "developer",
            "content": (
                "You are a deterministic FastAPI application generator.\n"
                "Return ONLY valid JSON matching the provided schema.\n"
                "No markdown fences. No commentary. No prose.\n\n"
                "Rules:\n"
                "- Output complete runnable files only.\n"
                "- Generate main.py and requirements.txt.\n"
                "- Use FastAPI.\n"
                "- Implement all endpoints in api.endpoints exactly.\n"
                "- Support GET and POST methods.\n"
                "- For POST endpoints, use Pydantic BaseModel request and response models.\n"
                "- Use response schema example values for static GET outputs.\n"
                "- For request/response mapping, map request.text to response.echo when the endpoint is /echo.\n"
                "- Keep the code minimal and executable.\n"
            ),
        },
        {
            "role": "user",
            "content": (
                f"Specification source: {spec_path.as_posix()}\n\n"
                f"Specification:\n{json.dumps(spec, indent=2, ensure_ascii=False)}\n\n"
                "Required output files:\n"
                "1. main.py\n"
                "2. requirements.txt\n"
            ),
        },
    ]


def normalise_content(content: str) -> str:
    content = content.strip()

    fenced = re.fullmatch(r"```[a-zA-Z0-9_-]*\n(.*)\n```", content, re.DOTALL)
    if fenced:
        content = fenced.group(1)

    if "```" in content:
        fail("Markdown fence detected in generated content.")

    return content


def validate_path(path_str: str) -> Path:
    if not path_str or not isinstance(path_str, str):
        fail("Validation failed: invalid file path.")

    if any(path_str.startswith(prefix) for prefix in FORBIDDEN_PREFIXES):
        fail(f"Validation failed: forbidden path {path_str}")

    path = Path(path_str)

    if path.is_absolute():
        fail(f"Validation failed: absolute path not allowed {path_str}")

    if ".." in path.parts:
        fail(f"Validation failed: path traversal detected {path_str}")

    return path


def validate_files(payload: dict, spec: dict) -> None:
    files = payload.get("files")

    if not isinstance(files, list) or not files:
        fail("Validation failed: no files returned.")

    by_path: dict[str, str] = {}

    for item in files:
        path = item.get("path")
        content = item.get("content")

        if not path or not isinstance(path, str):
            fail("Validation failed: invalid file path.")

        if not content or not isinstance(content, str):
            fail(f"Validation failed: empty content in {path}")

        if len(content.strip()) < 10:
            fail(f"Validation failed: content too short in {path}")

        if "```" in content:
            fail(f"Validation failed: markdown fence detected in {path}")

        validate_path(path)
        by_path[path] = normalise_content(content)

    if "main.py" not in by_path:
        fail("Validation failed: main.py missing.")

    if "requirements.txt" not in by_path:
        fail("Validation failed: requirements.txt missing.")

    main_py = by_path["main.py"]
    requirements_txt = by_path["requirements.txt"].lower()

    if "from fastapi import fastapi" not in main_py.lower() and "from fastapi import FastAPI" not in main_py:
        fail("Validation failed: FastAPI import missing in main.py")

    if "app = FastAPI()" not in main_py:
        fail("Validation failed: app instance missing in main.py")

    if "fastapi" not in requirements_txt:
        fail("Validation failed: fastapi missing in requirements.txt")

    if "uvicorn" not in requirements_txt:
        fail("Validation failed: uvicorn missing in requirements.txt")

    endpoints = to_contract_spec(spec)["api"]["endpoints"]

    for ep in endpoints:
        method = ep["method"].lower()
        path = ep["path"]
        decorator = f'@app.{method}("{path}")'
        if decorator not in main_py:
            fail(f"Validation failed: endpoint decorator missing {decorator}")

        if method == "post" and "BaseModel" not in main_py:
            fail("Validation failed: BaseModel missing for POST endpoint support")

    if any(ep["method"].upper() == "POST" for ep in endpoints):
        if "@app.post" not in main_py:
            fail("Validation failed: POST endpoint missing in main.py")


def write_files(payload: dict) -> None:
    for item in payload["files"]:
        path = validate_path(item["path"])
        content = normalise_content(item["content"])
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content + ("\n" if not content.endswith("\n") else ""), encoding="utf-8")
        print(f"WROTE {path.as_posix()}")


def generate_from_spec(spec_path: Path, spec: dict) -> None:
    messages = build_generation_messages(spec_path, spec)
    payload = call_openai_json(messages, OUTPUT_SCHEMA)
    validate_files(payload, spec)
    write_files(payload)


def main() -> None:
    spec_path, spec = read_spec()
    goal_data = read_json(GOAL_PATH, {"goal": ""})
    queue_data = read_json(QUEUE_PATH, {"goal": "", "tasks": []})
    state_data = read_json(
        STATE_PATH,
        {
            "goal": "",
            "status": "idle",
            "current_index": 0,
            "completed": [],
        },
    )

    goal = str(goal_data.get("goal", "")).strip()
    if not goal:
        fail("goal.json exists but contains no goal.")

    print(f"USING SPEC {spec_path.as_posix()}")
    print(f"GOAL: {goal}")

    goal_changed = state_data.get("goal") != goal

    if goal_changed:
        planned_tasks = plan_tasks(goal, spec)
        queue_data = {
            "goal": goal,
            "tasks": planned_tasks,
        }
        state_data = {
            "goal": goal,
            "status": "planned",
            "current_index": 0,
            "completed": [],
        }
        write_json(QUEUE_PATH, queue_data)
        write_json(STATE_PATH, state_data)
        print(f"PLANNED TASKS: {planned_tasks}")

    tasks = queue_data.get("tasks", [])
    current_index = int(state_data.get("current_index", 0))

    if not tasks:
        print("NO TASKS PLANNED. GENERATING FROM CURRENT SPEC.")
        spec = to_contract_spec(spec)
        save_spec(spec_path, spec)
        generate_from_spec(spec_path, spec)
        state_data["status"] = "completed"
        write_json(STATE_PATH, state_data)
        print("BOOTSTRAP COMPLETE")
        return

    while current_index < len(tasks):
        task_id = tasks[current_index]
        print(f"APPLYING TASK: {task_id}")

        spec = apply_task(spec, task_id)
        save_spec(spec_path, spec)

        generate_from_spec(spec_path, spec)

        state_data["status"] = "running"
        state_data["current_index"] = current_index + 1
        completed = list(state_data.get("completed", []))
        if task_id not in completed:
            completed.append(task_id)
        state_data["completed"] = completed
        write_json(STATE_PATH, state_data)

        current_index += 1

    state_data["status"] = "completed"
    write_json(STATE_PATH, state_data)
    print("BOOTSTRAP COMPLETE")


if __name__ == "__main__":
    main()
